name: White Paper
markdown: kramdown
url: https://thehuijb.github.io/vimsheet
description: A Great Vim Cheat Sheet

# Owner/author information
owner:
  name: Serge Huijben


theme: jekyll-theme-cayman
